### ISSUE TITLE
Empty event

### ISSUE THREAD

**Issue by Blshka** [soderlind/icalendar-ninja-forms#13]
Hi there, 
I was trying to implement sending iCal to users who register for an event (through the Ninja forms) and followed all steps on how to add iCal. 
Everything seems to be fine, however when the email is received, and I click on the "Add the event to the calendar" instead of adding event to the iCalendar I get message that the event is empty , or I have been redirected to the domain that the form was submitted from. 
Could you please advise what am I doing wrong and how to fix this?
Thank you

**Comment by Blshka** [comment]
UPDATE: I juste checked error logs and i'm getting this error messages as below, any chance someone would know to tell me what exactly am I missing and how to fix it?

`[09-Nov-2024 22:24:46 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Eluceo\iCal\Presentation\mb_strcut() in /home/grumpyowl/auringcentralmarketing.com.au/wp-content/plugins/icalendar-ninja-forms-main/vendor/eluceo/ical/src/Presentation/ContentLine.php:31
Stack trace:
#0 [internal function]: Eluceo\iCal\Presentation\ContentLine->__toString()
#1 /home/grumpyowl/auringcentralmarketing.com.au/wp-content/plugins/icalendar-ninja-forms-main/vendor/eluceo/ical/src/Presentation/Component.php(57): implode()
#2 /home/grumpyowl/auringcentralmarketing.com.au/wp-content/plugins/icalendar-ninja-forms-main/src/Invitation.php(117): Eluceo\iCal\Presentation\Component->__toString()
#3 /home/grumpyowl/auringcentralmarketing.com.au/wp-includes/class-wp-hook.php(324): Soderlind\NinjaForms\iCalendar\Invitation->card()
#4 /home/grumpyowl/auringcentralmarketing.com.au/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#5 /home/grumpyowl/auringcentralmarketing.com.au/wp-includes/plugin.php(565): WP_Hook->do_action()
#6 /home/grumpyowl/auringcentralmarketing.com.au/wp-includes/class-wp.php(418): do_action_ref_array()
#7 /home/grumpyowl/auringcentralmarketing.com.au/wp-includes/class-wp.php(813): WP->parse_request()
#8 /home/grumpyowl/auringcentralmarketing.com.au/wp-includes/functions.php(1336): WP->main()
#9 /home/grumpyowl/auringcentralmarketing.com.au/wp-blog-header.php(16): wp()
#10 /home/grumpyowl/auringcentralmarketing.com.au/index.php(17): require('/home/grumpyowl...')
#11 {main}
  thrown in /home/grumpyowl/auringcentralmarketing.com.au/wp-content/plugins/icalendar-ninja-forms-main/vendor/eluceo/ical/src/Presentation/ContentLine.php on line 31`

**Comment by Blshka** [comment]
UPDATE :I just checked the error logs and these messages below are coming up. Would anyone know what am I missing and how to fix it?


[09-Nov-2024 22:24:46 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Eluceo\iCal\Presentation\mb_strcut() in /home/wp-content/plugins/icalendar-ninja-forms-main/vendor/eluceo/ical/src/Presentation/ContentLine.php:31
Stack trace:
#0 [internal function]: Eluceo\iCal\Presentation\ContentLine->__toString()
#1 /home/wp-content/plugins/icalendar-ninja-forms-main/vendor/eluceo/ical/src/Presentation/Component.php(57): implode()
#2 /home/wp-content/plugins/icalendar-ninja-forms-main/src/Invitation.php(117): Eluceo\iCal\Presentation\Component->__toString()
#3 /home/wp-includes/class-wp-hook.php(324): Soderlind\NinjaForms\iCalendar\Invitation->card()
#4 /home/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#5 /home/wp-includes/plugin.php(565): WP_Hook->do_action()
#6 /home/wp-includes/class-wp.php(418): do_action_ref_array()
#7 /home/wp-includes/class-wp.php(813): WP->parse_request()
#8 /home/wp-includes/functions.php(1336): WP->main()
#9 /home/wp-blog-header.php(16): wp()
#10 /home/index.php(17): require('/home/grumpyowl...')
#11 {main}
  thrown in /home/wp-content/plugins/icalendar-ninja-forms-main/vendor/eluceo/ical/src/Presentation/ContentLine.php on line 31
